version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bank_statement_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/bank.db:/app/bank.db
    environment:
      DATABASE_URL: sqlite:///./bank.db
      SECRET_KEY: ${SECRET_KEY:-Xjb9-2BNOFQj7oA3zbYYT9Q9rbcKid1Uv5fZJvvpEng}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bank_statement_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/.env:/app/.env
    environment:
      VITE_API_URL: http://backend:8000/api/v1
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
